In [1]:
# Install via terminal
# pip install numpy

import numpy as np

# Verify installation and check version
print(np.__version__)

2.5.1


# creating multidimensional array

In [ ]:
# 1D Array
a = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
b = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in initializers
zeros = np.zeros((3, 3))        # 3x3 matrix of 0.0
ones = np.ones((2, 4))          # 2x4 matrix of 1.0
arange = np.arange(0, 10, 2)    # Array from 0 to 8, stepping by 2
linspace = np.linspace(0, 1, 5) # 5 evenly spaced numbers between 0 and 1


# array slicing

In [3]:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Get a specific element [row, column]
print(arr[1, 2]) # Returns 7

# Slice rows and columns
print(arr[0:2, 1:3]) # Top-left 2x2 sub-array

# Get entire row or column
print(arr[1, :])  # Second row: [5, 6, 7, 8]
print(arr[:, 2])  # Third column: [3, 7, 11]

7
[[2 3]
 [6 7]]
[5 6 7 8]
[ 3  7 11]


# arithmetic operations

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)  # [5, 7, 9]
print(x * y)  # [4, 10, 18]
print(x ** 2) # [1, 4, 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


# array broadcasting

In [5]:
# Multiplying a matrix by a single scalar
matrix = np.array([[1, 2], [3, 4]])
print(matrix * 2) # [[2, 4], [6, 8]]

# Example: 10x10 multiplication table exercise
row = np.arange(1, 11).reshape(1, 10)
col = np.arange(1, 11).reshape(1, 10)
grid = row * col

[[2 4]
 [6 8]]


# aggregate functions

In [6]:
data = np.array([[1, 2], [3, 4]])

print(data.sum())  # Sum of all elements: 10
print(data.min())  # Minimum value: 1
print(data.max())  # Maximum value: 4
print(data.mean()) # Average: 2.5
print(data.std())  # Standard deviation

# Aggregate down specific axes
print(data.sum(axis=0)) # Sum of each column: [4, 6]
print(data.sum(axis=1)) # Sum of each row: [3, 7]

10
1
4
2.5
1.118033988749895
[4 6]
[3 7]


# filtering (boolean masking)

In [7]:
numbers = np.array([10, 15, 20, 25, 30])

# Create a boolean mask
mask = numbers > 20 # [False, False, False, True, True]

# Filter using the mask
filtered_nums = numbers[mask] # [25, 30]

# Shortcut inline statement
print(numbers[numbers % 2 == 0]) # Even numbers: [10, 20, 30]

[10 20 30]


# random numbers

In [8]:
# Initialize the RNG object
rng = np.random.default_rng(seed=42) # Seed forces reproducibility

# Generate random integers (min inclusive, max exclusive)
rand_ints = rng.integers(low=1, high=7, size=5) # 5 dice rolls

# Generate uniform floating-point values between 0 and 1
rand_floats = rng.uniform(low=0.0, high=1.0, size=(2, 3))

# Shuffle an array in-place
arr_to_shuffle = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr_to_shuffle)

# Make a random selection from an array
fruits = np.array(['apple', 'banana', 'cherry'])
choice = rng.choice(fruits, size=10) # Chooses 10 random items