# import numpy

In [78]:
import numpy as np

print(np.__version__)

2.5.1


# array manipulation

In [79]:
arr = np.array(10)
print(arr)

arr9 = np.array([2,1,5,4,3])

arr2 = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr2)

arr1 = np.ones(10) # initializes with 10 ones
print(arr1)

arr0 = np.zeros(5) # initializes with 5 zeros
print(arr0)

arrx = np.empty(10) # initializes with random numbers
print(arrx)

lst = [19,14,26,17]
arr3 = np.array(lst)
print(arr3)

print(np.sort(arr3))
print(arr3 >= 20)

10
[ 0  1  2  3  4  5  6  7  8  9 10]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[19 14 26 17]
[14 17 19 26]
[False False  True False]


In [80]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

# concatenation
arr = np.concatenate((arr1,arr2))
print(arr)

# stacking
arrs = np.vstack((arr1,arr2))
print(arrs)

[1 2 3 4 5 5 6 7 8 9]
[[1 2 3 4 5]
 [5 6 7 8 9]]


# array slicing

In [81]:
# array slicing
arr2 = np.array([0,1,2,3,4,5,6,7,8,9,10])

print(arr2[3:8]) # from 3rd idx to 7th idx
print(arr2[3:8:2]) # from 3rd idx to 7th idx, gap 2

[3 4 5 6 7]
[3 5 7]


In [82]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.ndim) # dimension of array

arr2 = np.array([[1,2,3] , [4,5,6]])

print("array shape: ")
print(arr2.shape) # (2, 3) = 2 rows, 3 columns

arr3 = np.array([[1,2,3], [4,5,6]], ndmin = 3) 
print(arr3.shape) # (1,2,3) = 1 row, 2 columns, 3 elements per column

<class 'numpy.ndarray'>
1
array shape: 
(2, 3)
(1, 2, 3)


# access elements

In [83]:
# access element
arr = np.array([[1,2,3], [4,5,6]], ndmin = 3) 

print(arr[0][0][1]) # method 1
print(arr[0,0,1]) # method 2


arr9 = np.array([2,1,5,4,3])
arr2 = np.array([40,21,25,31,43,52,46,17,82,96,10])

arr4 = arr2[arr9] # accesses arr2 elements of arr9 indices
print(arr4)

2
2
[25 21 52 43 31]


# array copy (2 types)

In [84]:
arr = np.array([[1,2,3],[4,5,6]])

arr1 = arr.copy() # new memory space
arr2 = arr.view() # no new memory space

print("\nbase of arr: ")
print(arr.base)

print("\nbase of arr1: ") # copy, so base = none
print(arr1.base)

print("\nbase of arr2: ") # view, so base = arr 
print(arr2.base)


base of arr: 
None

base of arr1: 
None

base of arr2: 
[[1 2 3]
 [4 5 6]]


# reshape array

In [85]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr2 = arr.reshape(1,1,2,5) # 1 x 1 x 2 x 5 = arr.size (careful)
arr3 = arr2.flatten() # 1 dimension

print(arr2)
print(arr3)

[[[[0 1 2 3 4]
   [5 6 7 8 9]]]]
[0 1 2 3 4 5 6 7 8 9]


## transpose

In [86]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])

tr1 = np.transpose(arr)
tr2 = arr.T
tr3 = arr.transpose()

print("main array:")
print(arr)

print("\ntranspose;")
print(tr1)
print("\n" , tr2)
print("\n" , tr3)

main array:
[[1 2 3 4 5]
 [6 7 8 9 0]]

transpose;
[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]

 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]

 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


# iterate n dimension array

In [87]:
arr = np.array([[1,2,3,4],[2,4,5,6],[5,6,8,0]])

for x in np.nditer(arr):
    print(x, end = ' ')

1 2 3 4 2 4 5 6 5 6 8 0 